Add EPICS_PACKAGE_SITE to allow changing of package directories
slac-epics/epics-base pull request #16
Opened 2024-03-15 20:34 UTC by JJL772

This can be overridden in CONFIG_SITE.local

The primary motivation here is our WIP deployment of EPICS on S3DF. On S3DF we have `/sdf/sw/epics/package`, on AFS we have `/afs/slac/package` and we only want one version of EPICS shared between the two.

I could use an environment variable here too, (i.e. `EPICS_PACKAGE_TOP` that would only be defined in the new S3DF env), but @ernestow and I feel that over-reliance on environment variables for this type of configuration is a potential footgun.

I think once AFS goes away, we can change the default to be /sdf/sw/epics/package in CONFIG_SITE and check that into git. I intentionally left it as /afs/slac/package to reduce the likelihood that someone's workflow breaks.

Open to suggestions for better ways to handle this!

2024-03-15 22:00 UTC, bhill-slac requested changes
This looks like a good way to handle the transition from AFS to S3DF.
My only suggestion would be to use SLAC_PACKAGE_TOP instead of EPICS_PACKAGE_TOP as the variable name since /afs/slac/package contains many packages that have little to do with EPICS.

2024-03-15 22:06 UTC, bhill-slac commented
My general comment is that PCDS may need their own version of this change since I think they still have a few older RTEMS IOCs.
Mike Browne may have a better idea of how many.    Also, see $CONFIG_SITE_TOP/common_dirs.sh for a different take on how to handle these differences in where packages and other common directories are located.     I think the RTEMS builds still had hard coded paths as they pre-dated my work in making eco_tools work for LCLS, PCDS, ACCL, PAL, etc, and we were already phasing out RTEMS in PCDS.

2024-03-15 22:15 UTC, ernestow commented
Great suggestion, Bruce.
I agree as well with using EPICS_PACKAGE_TOP



Cheers,
Ernest
________________________________
From: Bruce Hill ***@***.***>
Sent: Friday, March 15, 2024 3:00 PM
To: slac-epics/epics-base ***@***.***>
Cc: Williams Jr., Ernest L. ***@***.***>; Mention ***@***.***>
Subject: Re: [slac-epics/epics-base] Add EPICS_PACKAGE_SITE to allow changing of package directories (PR #16)


@bhill-slac requested changes on this pull request.

This looks like a good way to handle the transition from AFS to S3DF.
My only suggestion would be to use SLAC_PACKAGE_TOP instead of EPICS_PACKAGE_TOP as the variable name since /afs/slac/package contains many packages that have little to do with EPICS.

—
Reply to this email directly, view it on GitHub<https://github.com/slac-epics/epics-base/pull/16#pullrequestreview-1940729490>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AB44BJF52FJWFPRRIKT6EFDYYNVQFAVCNFSM6AAAAABEYT5VXWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNBQG4ZDSNBZGA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-03-15 22:34 UTC, JJL772 commented
Alright, I've renamed it from EPICS_PACKAGE_TOP to SLAC_PACKAGE_TOP

Should be obvious who added it now :smile:

2024-03-15 22:36 UTC, ernestow commented
We actually have the following:
"/afs/slac/package"   ===> legacy location but Till and I decided leave linuxRT and RTEMS.
"/afs/slac/g/lcls/package" ==> new home for packages.  I recommend that both linuxRT and RTEMS be moved here for future releases.
"/afs/slac/g/lcls/package/pkg_mgr"  ==> package area for PCDS which was managed by Bruce.

For unification on S3DF, there will be only one package area for everyone.

2024-03-15 22:43 UTC, ernestow approved these changes

2024-03-16 00:16 UTC, bhill-slac commented
Note that $PACKAGE_SITE_TOP/pkg_mgr is used for automated package builds for eco_tools,
and thus both LCLS and PCDS EPICS build system.    They access that path via PSPKG_ROOT.

The other directories under $PACKAGE_SITE_TOP are for misc packages that have more manual unpack and build systems.

For S3DF unification, you'll need both $PACKAGE_SITE_TOP and $PSPKG_ROOT.
A common default for PSPKG_ROOT is $PACKAGE_SITE_TOP/pkg_mgr.

On 3/15/2024 3:36 PM, Ernest Williams wrote:

We actually have the following:
"/afs/slac/package" ===> legacy location but Till and I decided leave linuxRT and RTEMS.
"/afs/slac/g/lcls/package" ==> new home for packages. I recommend that both linuxRT and RTEMS be moved here for future releases.
"/afs/slac/g/lcls/package/pkg_mgr" ==> package area for PCDS which was managed by Bruce.

For unification on S3DF, there will be only one package area for everyone.

—
Reply to this email directly, view it on GitHub<https://github.com/slac-epics/epics-base/pull/16#issuecomment-2000590141>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABPDOJXTNUPP5OWZHAK6IHLYYNZWPAVCNFSM6AAAAABEYT5VXWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMBQGU4TAMJUGE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-03-18 17:42 UTC, JJL772 commented
@bhill-slac Does this PR look OK now? I've renamed EPICS_PACKAGE_TOP -> SLAC_PACKAGE_TOP, as requested. Unless I misunderstood something :)

2024-03-20 07:42 UTC, bhill-slac approved these changes
Looks good!

2024-03-20 15:35 UTC, merged